name: Test Bookmarklets

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x, 22.x, 24.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Node.js ${{ matrix.node-version }} セットアップ
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: 依存関係インストール
      run: npm ci

    - name: テスト実行
      run: npm test -- --verbose

    - name: カバレッジ付きテスト実行
      run: npm run test:coverage

    - name: カバレッジレポート生成
      if: github.event_name == 'pull_request'
      run: |
        echo "## Test Coverage Report" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        if [ -f "packages/bookmarklet/coverage/coverage-summary.json" ]; then
          node -e "
            const fs = require('fs');
            const coverage = JSON.parse(fs.readFileSync('packages/bookmarklet/coverage/coverage-summary.json', 'utf8'));
            const total = coverage.total;
            console.log('| Metric | Coverage | Status |');
            console.log('|--------|----------|--------|');
            console.log(\`| Lines | \${total.lines.pct}% | \${total.lines.pct >= 80 ? '✅' : '❌'} |\`);
            console.log(\`| Functions | \${total.functions.pct}% | \${total.functions.pct >= 80 ? '✅' : '❌'} |\`);
            console.log(\`| Branches | \${total.branches.pct}% | \${total.branches.pct >= 80 ? '✅' : '❌'} |\`);
            console.log(\`| Statements | \${total.statements.pct}% | \${total.statements.pct >= 80 ? '✅' : '❌'} |\`);
          " >> $GITHUB_STEP_SUMMARY
        fi
